name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - 2.2.1-Pages
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.DOXYGEN_TOKEN }}
          branch: gh-pages-2.2.1
          folder: src/
          config_file: Doxyfile
