  - name: Doxygen Action
  - uses: mattnotmitt/doxygen-action@1.9.5
  with:
    # Path to Doxyfile
    doxyfile-path: # default is ./Doxyfile
    # Working directory
    working-directory: # default is .
    # Generate latex documentation
    enable-latex: # optional
    # Extra alpine packages for the build environment
    additional-packages: # optional, default is
